export default [
  {
    _id: "Q101",
    title: "Rocket Propulsion Quiz",
    course: "RS101",
    description: "Test your knowledge of rocket propulsion",
    points: 100,
    dueDate: "2024-05-13T23:59",
    availableFrom: "2024-05-06T12:00",
    availableUntil: "2024-05-20T23:59",
    published: false,
    questions: [],
    type: "Graded Quiz",
    assignmentGroup: "Quizzes",
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
  },
  {
    _id: "Q102",
    title: "Rocket Propulsion Quiz Part 2",
    course: "RS101",
    description: "Test your knowledge of rocket propulsion and engineering",
    points: 130,
    dueDate: "2024-05-13T23:59",
    availableFrom: "2024-05-06T12:00",
    availableUntil: "2024-05-20T23:59",
    published: false,
    questions: [],
    type: "Graded Quiz",
    assignmentGroup: "Quizzes",
    shuffleAnswers: true,
    timeLimit: 160,
    multipleAttempts: false,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
  },
];
